on:
  workflow_dispatch:

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Collect system information
        run: |
          echo "OS: ${{ runner.os }}"
          echo "Runner name: ${{ runner.name }}"
          echo "Runner architecture: ${{ runner.arch }}"
          echo "OS Details"
          uname -a
          cat /etc/os-release
          echo "1. CPU Information"
          lscpu
          echo "2. Memory Information"
          free -h
          echo "3. Disk Information"
          df -h
